export default {
    LANDING: '/',
    CUSTOMERS: '/customers',
    WORK_ORDERS: '/workorders',
    INVOICES: '/invoices',
    COSTS: '/costs',
    ARCHIVED: '/archived',
    JOBS: '/jobs',
    SIGN_UP: '/signup',
    SIGN_IN: '/signin',
    HOME: '/home',
    ACCOUNT: '/account',
    PASSWORD_FORGET: '/pw-forget',
    ADMIN: '/admin',
}
